/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.net.*;
import java.time.Duration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.Predicate;
import java.util.function.Supplier;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.devtools.DevTools;
import org.openqa.selenium.devtools.HasDevTools;
import org.openqa.selenium.devtools.NetworkInterceptor;
import org.openqa.selenium.devtools.v130.browser.Browser;
import org.openqa.selenium.devtools.v130.network.Network;
import org.openqa.selenium.devtools.v130.performance.Performance;
import org.openqa.selenium.devtools.v130.performance.model.Metric;
import org.openqa.selenium.remote.http.*;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.Cookie;
import org.openqa.selenium.chromium.HasCdp;

public class App {
    
    public static void main(String[] args) throws Exception{
        
        WebDriver driver = new ChromeDriver();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

        CopyOnWriteArrayList<String> contentType = new CopyOnWriteArrayList<>();
        CopyOnWriteArrayList<Contents.Supplier> content = new CopyOnWriteArrayList<>();

        Filter myFilter = next -> {
            return req -> {
                HttpResponse res = next.execute(req);
                contentType.add(res.getHeader("Content-Type"));
                content.add(res.getContent()); 
                return res;
            };
        };
        
        NetworkInterceptor ignored = new NetworkInterceptor(driver, myFilter);
        
        
        driver.get("https://www.selenium.dev/selenium/web/blank.html");
        wait.until(_d -> contentType.size() > 1);
        
        System.out.println(contentType.get(0));
        
        String result = new String(content.get(0).get().readAllBytes());
        System.out.println(result);
        

        driver.quit();


        

    }
}
