/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.nio.charset.StandardCharsets;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import com.google.genai.Client;
import com.google.genai.types.GenerateContentResponse;
import java.util.regex.*;
import java.util.*;
import java.net.*;
import java.time.Duration;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.Predicate;
import java.util.function.Supplier;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.devtools.DevTools;
import org.openqa.selenium.devtools.HasDevTools;
import org.openqa.selenium.devtools.NetworkInterceptor;
import org.openqa.selenium.devtools.v141.browser.Browser;
import org.openqa.selenium.devtools.v141.network.Network;
import org.openqa.selenium.devtools.v141.performance.Performance;
import org.openqa.selenium.devtools.v141.performance.model.Metric;
import org.openqa.selenium.remote.http.*;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.chromium.HasCdp;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;


public class App {

    // Keywords for cookie policy URLs (multiple EU languages)
    private static final List<String> COOKIE_KEYWORDS = Arrays.asList(
        // Español
        "cookies", "cookie", "politica-de-cookies", "política-de-cookies", "politica-galetes",
        // Inglés
        "cookie-policy", "cookies-policy", "cookie", "cookies", "cookie-settings", "cookies-settings", "cookie-declaration", "cookie-notice", "cookies-terms", "information-about-cookies",
        // Francés
        "politique-de-cookies", "cookies-et-traceurs", "gestion-des-cookies", "charte-cookies",
        // Alemán
        "cookie-richtlinie", "cookie-einstellungen", "cookie-erklaerung", "cookie-erklaerklärung",
        // Italiano
        "cookie-policy", "informativa-cookie", "uso-dei-cookie", "policy-cookie",
        // Portugués
        "politica-de-cookies", "política-de-cookies", "informacion-cookies", "termos-cookies",
        // Neerlandés 
        "cookiebeleid", "cookieverklaring", "cookies-instellen", "cookie-statement",
        // Danés
        "cookiepolitik", "om-cookies", "cookie-deklaration",
        // Sueco
        "cookiepolicy", "kakor", "om-kakor", "cookie-installningar", "cookie-inställningar",
        // Noruego
        "informasjonskapsler", "cookie-erklaring","cookie-erklæring",
        // Finlandés (Finno-ugrio)
        "evasteet", "evastekaytanto", "evastepolitiikka",
        // Polaco
        "polityka-plikow-cookies", "polityka-cookies", "ciasteczka",
        // Checo / Eslovaco
        "zasady-pouzivani-cookies", "prohlaseni-o-cookies", "nastavenia-cookies", "nastaveni-cookies", "zasady-cookies",
        // Rumano
        "politica-de-cookie", "despre-cookie", "cookies-modul",
        // Esloveno / Croata
        "piskotki", "politika-piskotkov", "kolacici", "politika-kolacica",
        // Húngaro
        "sutik", "suti-kezeles", "cookie-tajekoztato", "sütibeállítások", "suti-tajekoztato",
        // Búlgaro 
        "politika-za-biskvitkite", "biskvitki",
        // Griego 
        "cookies-politiki", "politiki-cookies",
        // Estonia
        "kupsised", "kupsiste-poliitika", "cookie-satted",
        // Letonia
        "sikdatnes", "sikdatnu-politika", "sikdatnu-izmantosana",
        // Lituania
        "slapukai", "slapuku-politika", "slapuku-nustatymai",
        // Ucrania
        "faily-cookie", "polityka-cookie", "vykorystannya-cookie", "nalashtuvannya-cookie",
        "cookie-policy-ua", "cookies-ua", "файли-cookie", "політика-cookie", "політика-щодо-cookie",
        "використання-cookie", "налаштування-cookie", "cookie-файли", "cookie-файлів"
    );

    // Keywords for privacy policy / data protection URLs 
    private static final List<String> PRIVACY_KEYWORDS = Arrays.asList(
        // Español
        "privacidad", "politica-de-privacidad", "política-de-privacidad", "proteccion-de-datos", "protección-de-datos", 
        // Inglés
        "privacy", "privacy-policy", "data-protection", 
        // Francés
        "confidentialite", "confidentialité", "politique-de-confidentialite", "politique-de-confidentialité", "politique-confidentialite",
        "donnees-personnelles", "données-personnelles", "politique-de-confidentialite",
        // Alemán
        "datenschutz", "datenschutzerklarung", "datenschutzerklärung", "datenschutzhinweis", "datenschutzerklaerung",
        // Italiano
        "privacy", "informativa-privacy", "protezione-dei-dati",
        // Portugués
        "privacidade", "politica-de-privacidade", "proteccao-de-dados", "proteção-de-dados",
        // Neerlandés
        "privacyverklaring", "gegevensbescherming", "persoonsgegevens",
        // Sueco
        "integritet", "personuppgifter", "dataskydd",
        // Danés
        "privatliv", "privatlivspolitik", "databeskyttelse",
        // Finés
        "tietosuoja", "tietosuojakaytanto", "tietosuojakäytäntö",
        // Griego
        "aporrito", "aporrito-prosopikon-dedomenon", "prostateia-dedomenon",
        // Checo
        "ochrana-osobnich-udaju", "ochrana-osobních-údajů", "osobni-udaje",
        // Eslovaco
        "ochrana-osobnych-udajov", "osobne-udaje",
        // Polaco
        "ochrona-danych", "ochrona-danych-osobowych", "polityka-prywatnosci", "polityka-prywatności",
        // Húngaro
        "adatvedelem", "adatkezelesi-tajekoztato", "adatkezelési-tájékoztató",
        // Rumano
        "confidentialitate", "politica-de-confidentialitate", "protectia-datelor", "protecția-datelor",
        // Búlgaro
        "zastita-na-lichnite-danni", "lichni-danni",
        // Croata
        "zastita-osobnih-podataka", "politika-privatnosti",
        // Esloveno
        "varstvo-osebnih-podatkov", "politika-zasebnosti",
        // Letón
        "privatuma-politika", "datu-aizsardziba", "datu-aizsardzība",
        // Lituano
        "privatumo-politika", "asmens-duomenu-apsauga",
        // Estonio
        "privaatsus", "privaatsustingimused", "isikuandmete-kaitse",
        // Maltés
        "privatezza", "politika-tal-privatezza", "protezzjoni-tad-data",
        // Irlandés
        "príobháideachas", "beartas-príobháideachais", "cosaint-sonraí",
        // Luxemburgués
        "dateschutz", "privatsphaer", "privatsphär",
        // Ucraniano
        "konfidentsiinist",  "polityka-konfidentsiinosti", "zakhyst-danykh", "personalni-dani","конфіденційність",
        "політика-конфіденційності", "захист-даних", "персональні-дані",
        // Chipriota 
        "prostateia-prosopikon-dedomenon"
    );

    private static final String URL = "jdbc:mysql://127.0.0.1:3306/TMA?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC";
    private static final String USER = "root";

    public static void main(String[] args) throws Exception {

        String geminiApiKey = System.getenv("GEMINI_API_KEY");
        String chromedriverAbsolutePath = System.getenv("CHROMEDRIVER_ABSOLUTE_PATH");
        String databasePassword = System.getenv("DATABASE_PASSWORD");

        if (geminiApiKey == null) {
            System.out.println("Environment variable GEMINI_API_KEY has not been exported. It is not possible to proceed.\nTo set it use this command 'export GEMINI_API_KEY=<key>'");
            return;
        }

        if (chromedriverAbsolutePath == null) {
            System.out.println("Environment variable CHROMEDRIVER_ABSOLUTE_PATH has not been exported. It is not possible to proceed.\nTo set it use this command 'export CHROMEDRIVER_ABSOLUTE_PATH=<absolute_path>'");
            return;
        }

        if (databasePassword == null) {
            System.out.println("Environment variable DATABASE_PASSWORD has not been exported. It is not possible to proceed.\nTo set it use this command 'export DATABASE_PASSWORD=<database_password>'");
            return;
        }

        // Read domains from a file (one URL per line, # for comments)
        List<String> domains = Files.readAllLines(Path.of("domains.txt"), StandardCharsets.UTF_8)
                .stream()
                .map(String::trim)
                .filter(line -> !line.isEmpty() && !line.startsWith("#"))
                .toList();

        if (domains.isEmpty()) {
            System.out.println("No domains found in domains.txt. Please add at least one URL.");
            return;
        }

        System.setProperty("webdriver.chrome.driver", chromedriverAbsolutePath);

        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless=new");
        options.addArguments("--disable-gpu");
        options.addArguments("--window-size=1920,1080");
        options.addArguments("--no-sandbox");
        options.addArguments("--disable-dev-shm-usage");

        WebDriver driver = new ChromeDriver(options);

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(15));

        CopyOnWriteArrayList<Contents.Supplier> content = new CopyOnWriteArrayList<>();

        Filter myFilter = next -> {
            return req -> {
                HttpResponse res = next.execute(req);
                content.add(res.getContent());
                return res;
            };
        };

        NetworkInterceptor ignored = new NetworkInterceptor(driver, myFilter);

        Client client = new Client();

        // Loop over all domains from domains.txt
        int counter = 0;
        for (String domain : domains) {

            System.out.println("\n\n========================================");
            System.out.println("Processing domain: " + domain);
            System.out.println("========================================\n");

            System.out.println("Checking database for domain: " + domain);

            // Check if this domain was already processed
            boolean alreadyProcessed = false;

            try (Connection connection = DriverManager.getConnection(URL, USER, databasePassword)) {

                String checkQuery = "SELECT 1 FROM host_results WHERE hostname = ? LIMIT 1";
                try (PreparedStatement checkStmt = connection.prepareStatement(checkQuery)) {
                    checkStmt.setString(1, domain);
                    try (ResultSet rs = checkStmt.executeQuery()) {
                        if (rs.next()) {
                            alreadyProcessed = true;
                        }
                    }
                }

            } catch (SQLException e) {
                System.err.println("Database error while checking existing domain: " + domain);
                e.printStackTrace();
                continue;
            }

            if (alreadyProcessed) {
                System.out.println("Domain FOUND in database, skipping processing: " + domain);
                continue;
            }

            System.out.println("Domain NOT found in database, proceeding with analysis: " + domain);


            // Clear previous captured contents
            content.clear();

            URI uri;
            try {
                uri = new URI(domain);
            } catch (URISyntaxException e) {
                System.out.println("Skipping invalid domain (URI syntax error): " + domain);
                continue;
            }

            String host = uri.getHost(); // e.g. "www.elmundo.es"
            if (host == null) {
                System.out.println("Skipping invalid domain (no host found): " + domain);
                continue;
            }

            String short_domain = host.startsWith("www.") ? host.substring(4) : host;

            // Navigate to the domain
            try {
                driver.get(domain);
            } catch (Exception e){
                System.out.println("Skipping non existing domain: " + domain);
                continue;
            }

            try {
                wait.until(_d -> content.size() > 150);
            } catch (org.openqa.selenium.TimeoutException e) {
                System.out.println("\nTimeout while waiting for network activity on: " + domain);
                System.out.println("Number of caught files: " + content.size());
            }

            //////////////////////////////////////////////////////////////////////////////

            List<String> urls = new ArrayList<>();

            for (int i = 0; i < content.size(); i++) {
                String result = new String(content.get(i).get().readAllBytes());

                // Regex to match https:// followed by any non-space characters
                String regex = "https://[^\\s]+";

                Pattern pattern = Pattern.compile(regex);
                Matcher matcher = pattern.matcher(result);

                while (matcher.find()) {
                    urls.add(matcher.group());
                }
            }

            String cookieUrlsSeparatedByCommas = "";
            String privacyUrlsSeparatedByCommas = "";

            // Filter and build URL list for cookies/privacy on this domain
            for (String url : urls) {

                String[] cuttedUrl = url.split("[\"'\\\\]");
                String normalizedUrl = cuttedUrl[0].toLowerCase();

                // Only consider URLs from this domain
                if (normalizedUrl.contains(short_domain)) {

                    boolean isCookie = false;
                    for (String keyword : COOKIE_KEYWORDS) {
                        if (normalizedUrl.contains(keyword)) {
                            isCookie = true;
                            break;
                        }
                    }

                    boolean isPrivacy = false;
                    for (String keyword : PRIVACY_KEYWORDS) {
                        if (normalizedUrl.contains(keyword)) {
                            isPrivacy = true;
                            break;
                        }
                    }

                    if (isCookie) {
                        cookieUrlsSeparatedByCommas = cookieUrlsSeparatedByCommas + cuttedUrl[0] + ", ";
                    }

                    if (isPrivacy) {
                        privacyUrlsSeparatedByCommas = privacyUrlsSeparatedByCommas + cuttedUrl[0] + ", ";
                    }
                }
            }

            // Debug:
            System.out.println("Cookie candidates for " + domain + ": " + cookieUrlsSeparatedByCommas);
            System.out.println("Privacy candidates for " + domain + ": " + privacyUrlsSeparatedByCommas);

            if (cookieUrlsSeparatedByCommas.isEmpty() && privacyUrlsSeparatedByCommas.isEmpty()) {
                System.out.println("No candidate URLs for cookies or privacy on domain: " + domain);

                insertIntoDatabase(databasePassword, domain, "{\"results\":\"URLs not found.\"}");

                continue; // pasa al siguiente dominio del for grande
            }
            if (!cookieUrlsSeparatedByCommas.isEmpty()) {
                cookieUrlsSeparatedByCommas =
                        cookieUrlsSeparatedByCommas.substring(0, cookieUrlsSeparatedByCommas.length() - 2);
            }
            if (!privacyUrlsSeparatedByCommas.isEmpty()) {
                privacyUrlsSeparatedByCommas =
                        privacyUrlsSeparatedByCommas.substring(0, privacyUrlsSeparatedByCommas.length() - 2);
            }
            ////////////////////////////////////////////////////////////

            //Cookie prompt → uses only cookie candidate URLs (unless none exist).
            //Privacy prompt → uses only privacy candidate URLs (unless none exist).
            
            // If one list is empty, fall back to the other so Gemini still has something to choose from
            String cookieCandidatesForPrompt  = cookieUrlsSeparatedByCommas.isEmpty()
                    ? privacyUrlsSeparatedByCommas
                    : cookieUrlsSeparatedByCommas;

            String privacyCandidatesForPrompt = privacyUrlsSeparatedByCommas.isEmpty()
                    ? cookieUrlsSeparatedByCommas
                    : privacyUrlsSeparatedByCommas;

            GenerateContentResponse responseCookie = client.models.generateContent(
                    "gemini-2.5-flash",
                    "From these URL's (" + cookieCandidatesForPrompt +
                    "), found when parsing " + short_domain +
                    " html and js files, which do you think is the cookie policy webpage. Just return one URL.",
                    null);

            System.out.println();
            System.out.println("Gemini guess for Cookies information (" + domain + "): " + responseCookie.text());

            GenerateContentResponse responsePrivacy = client.models.generateContent(
                    "gemini-2.5-flash",
                    "From these URL's (" + privacyCandidatesForPrompt +
                    "), found when parsing " + short_domain +
                    " html and js files, which do you think is the privacy policy webpage. Just return one URL.",
                    null);

            System.out.println();
            System.out.println("Gemini guess for Privacy information (" + domain + "): " + responsePrivacy.text());


            ////////////////////////////////////////////////////////////

            try {
                ProcessBuilder builder = new ProcessBuilder("bash", "-c", "wget -P ./cookies --no-check-certificate -p -k " + responseCookie.text());
                Process process = builder.start();
                int exitCode = process.waitFor();

                builder = new ProcessBuilder("bash", "-c", "wget -P ./privacidad --no-check-certificate -p -k " + responsePrivacy.text());
                process = builder.start();
                exitCode = process.waitFor();

            } catch (Exception e) {
                e.printStackTrace();
            }

            // NEW VERSION TO CHECK URL
            String privacyHtml = "";
            String cookiesHtml = "";

            try {
                // Clean URLs returned by Gemini (just in case there are spaces or newlines)
                String cookieUrl  = responseCookie.text().trim();
                String privacyUrl = responsePrivacy.text().trim();

                // Build URIs from those URLs
                URI cookieUri  = new URI(cookieUrl);
                URI privacyUri = new URI(privacyUrl);

                // Extract real host and path as downloaded by wget
                String cookieHost   = cookieUri.getHost();   // e.g. "elpais.com"
                String cookiePath   = cookieUri.getPath();   // e.g. "/info/politica-de-cookies/"
                String privacyHost  = privacyUri.getHost();  // e.g. "english.elpais.com"
                String privacyPath  = privacyUri.getPath();  // e.g. "/info/cookies-policy/"

                // Build local file paths, matching wget -P ./cookies -p -k <url>
                String cookiesFilePath  = "./cookies/"    + cookieHost   + cookiePath;
                String privacyFilePath  = "./privacidad/" + privacyHost  + privacyPath;

                // If the path ends with '/', assume index.html
                if (cookiesFilePath.endsWith("/")) {
                    cookiesFilePath += "index.html";
                }
                if (privacyFilePath.endsWith("/")) {
                    privacyFilePath += "index.html";
                }

                System.out.println("Reading cookies file from:  " + cookiesFilePath);
                System.out.println("Reading privacy file from: " + privacyFilePath);

                cookiesHtml = Files.readString(Path.of(cookiesFilePath), StandardCharsets.ISO_8859_1);
                privacyHtml = Files.readString(Path.of(privacyFilePath), StandardCharsets.ISO_8859_1);

            } catch (Exception e) {
                System.err.println("Error reading policy files for domain " + domain + ": " + e.getMessage());
                e.printStackTrace();
            }
            //NEW VERSION TO CHECK URL


            String promptArray[] = new String[3];

            promptArray[0] = """

            Role: Act as a Senior GDPR and ePrivacy Compliance Auditor.

            Task: You will analyze the content of two provided legal documents in HTML format (Privacy Policy and Cookie Policy) against a specific compliance checklist and output the results in a strict JSON format.

            Input Data:
            
            """;

            promptArray[1] =
                    "\nPrivacy Policy HTML file: [" + privacyHtml + "]" +
                    "\nCookie Policy HTML file: [" + cookiesHtml + "]" +
                    "\nCookies inventory: not provided";

            promptArray[2] = """

            Instructions:

            Read and analyze the content of the documents provided above.

            Evaluate the "Audit Checklist" questions below.

            CRITICAL: For every answer, determine the "Verdict" (Yes / No / Partial) and extract "Evidence" (direct quote).

            SCORING: Calculate the score internally:

            Yes = 2 points

            Partial = 1 point

            No/Not Found = 0 points

            Total possible: 34 points.

            Levels: 0-15 (Critical Risk), 16-24 (High Risk), 25-30 (Moderate Risk), 31-34 (Low Risk / Compliant).

            AUDIT CHECKLIST (To be analyzed):

            PART A: GENERAL GOVERNANCE & DATA SUBJECT RIGHTS

            Does the policy clearly state the full contact details of the Data Controller (company name, address) and the Data Protection Officer (DPO), if applicable?

            Does the policy specify the retention period (how long data is kept) for the main categories of personal data collected?

            Does the policy list the specific user rights (Access, Rectification, Erasure, Objection, Portability)?

            Is there an operational contact channel (specific email or form) and clear instructions on how to exercise these rights?

            Is the right to lodge a complaint with the relevant supervisory authority mentioned?

            If data leaves the EEA, does the policy identify the recipient country and the specific safeguards used (e.g., Standard Contractual Clauses/SCCs or Data Privacy Framework)?

            PART B: COOKIES & TRACKING TRANSPARENCY 7. Is there a specific and accessible Cookie Policy? (Is it separate or clearly integrated within the Privacy Policy?) 8. Does it explain in plain language what cookies are and why they are used on this website? 9. Are cookie categories clearly defined? (e.g., Technical, Analytical, Marketing, Preferences). 10. Are "strictly necessary" cookies explained, and is it justified why these do not require prior consent? 11. Does the policy contain a table or list detailing every cookie, including: Name, Provider, Purpose, and Duration? 12. Are there links to the privacy policies of external providers (third parties like Google, Facebook)? 13. Does it explicitly state that non-essential cookies (analytics/marketing) are only installed after consent? 14. Is the legal basis identified for each cookie type? (e.g., "Legitimate Interest/Necessity" for essential ones; "Consent" for the rest). 15. Does the text explain how the user can withdraw or modify their consent at any time? (Must mention a settings panel, footer link, or similar). 16. Does it clarify that withdrawing consent is as easy as giving it (e.g., "you can change your mind at any time")? 17. Does it mention if cookies are used for user profiling or tracking?

            OUTPUT FORMAT (STRICT JSON)
            Provide the response ONLY as a valid JSON object. Do not include introductory text or markdown formatting (like ```json). Use exactly the following structure:

            JSON

            {
              "audit_meta": {
                "auditor_role": "Senior GDPR & ePrivacy Compliance Auditor",
                "documents_reviewed": [
                  "Privacy Policy",
                  "Cookie Policy"
                ],
              },
              "audit_checklist": [
                {
                  "id": 1,
                  "category": "PART A: GENERAL GOVERNANCE",
                  "question": "Insert the FULL question text here",
                  "verdict": "Yes / No / Partial",
                  "evidence": "Insert direct quote here",
                  "notes": "Insert your auditor analysis here"
                },
                {
                  "id": 2,
                  "...": "..."
                }
                // Continue for all 17 questions
              ],
              "scorecard": {
                "total_score": 0, // Sum of points
                "max_score": 34,
                "compliance_level": "INSERT LEVEL NAME",
                "risk_icon": "🔴 / 🟠 / 🟡 / 🟢",
                "reasons": "INSERT A SHORT SUMMARY OF THE EVIDENCES OBTAINED",
                "priority_actions": [
                  "Action 1 based on negative results",
                  "Action 2 based on negative results",
                  "Action 3 based on negative results"
                ]
              }
            }

            """;

            GenerateContentResponse responseGDPR = client.models.generateContent(
                    "gemini-2.5-flash",
                    promptArray[0] + promptArray[1] + promptArray[2],
                    null);

            System.out.println();
            System.out.println("Gemini GDPR response for domain " + domain + ": " + responseGDPR.text());

            String responseGDPRProcessed = responseGDPR.text().trim();
            if ((responseGDPRProcessed.charAt(0)=='`')) {
                responseGDPRProcessed = responseGDPRProcessed.substring(7, responseGDPRProcessed.length() - 3);
            }
            insertIntoDatabase(databasePassword, domain, responseGDPRProcessed);

            counter++;
            if(counter == 5){
                System.out.println("5 Domains processed. Sleeping for 30 seconds.");
                Thread.sleep(30000);
                counter = 0;
            }
        }

        driver.quit();
        Runtime.getRuntime().exec("rm -rf privacidad");
        Runtime.getRuntime().exec("rm -rf cookies");
    }

    public static void insertIntoDatabase(String databasePassword, String domain, String jsonToInsert){

        try (Connection connection = DriverManager.getConnection(URL, USER, databasePassword)) {

        String query = "INSERT INTO host_results (hostname, results) VALUES (?, ?)";
        
        PreparedStatement ps = null;
        ps = connection.prepareStatement(query);
        ps.setString(1, domain);
        ps.setString(2, jsonToInsert);  
        //ps.execute();
        //instead of ps.execute, we want to verify if data is saved
        int rows = ps.executeUpdate();
        System.out.println("DB insert rows affected: " + rows + " for domain " + domain);

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }
}

