/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.nio.charset.StandardCharsets;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import com.google.genai.Client;
import com.google.genai.types.GenerateContentResponse;
import java.util.regex.*;
import java.util.*;
import java.net.*;
import java.time.Duration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.Predicate;
import java.util.function.Supplier;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.devtools.DevTools;
import org.openqa.selenium.devtools.HasDevTools;
import org.openqa.selenium.devtools.NetworkInterceptor;
import org.openqa.selenium.devtools.v141.browser.Browser;
import org.openqa.selenium.devtools.v141.network.Network;
import org.openqa.selenium.devtools.v141.performance.Performance;
import org.openqa.selenium.devtools.v141.performance.model.Metric;
import org.openqa.selenium.remote.http.*;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.Cookie;
import org.openqa.selenium.chromium.HasCdp;

public class App {
    
    public static void main(String[] args) throws Exception{
        
        String geminiApiKey = System.getenv("GEMINI_API_KEY");
        String chromedriverAbsolutePath = System.getenv("CHROMEDRIVER_ABSOLUTE_PATH");
        
        if (geminiApiKey == null) {
            System.out.println("Environment variable GEMINI_API_KEY has not been exported. It is not possible to proceed.\nTo set it use this command 'export GEMINI_API_KEY=<key>'");
            return;
        }

        if (chromedriverAbsolutePath == null) {
            System.out.println("Environment variable CHROMEDRIVER_ABSOLUTE_PATH has not been exported. It is not possible to proceed.\nTo set it use this command 'export CHROMEDRIVER_ABSOLUTE_PATH=<absolute_path>'");
            return;
        }

        System.setProperty("webdriver.chrome.driver", chromedriverAbsolutePath);
        
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless=new");
        options.addArguments("--disable-gpu"); 
        options.addArguments("--window-size=1920,1080");
        options.addArguments("--no-sandbox");
        options.addArguments("--disable-dev-shm-usage");
        
        WebDriver driver = new ChromeDriver(options);

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(15));

        CopyOnWriteArrayList<Contents.Supplier> content = new CopyOnWriteArrayList<>();

        Filter myFilter = next -> {
            return req -> {
                HttpResponse res = next.execute(req);
                if(res.getHeader("Content-Length") != null && Integer.parseInt(res.getHeader("Content-Length")) !=0){
                    content.add(res.getContent());
                }
                return res;
            };
        };
        
        NetworkInterceptor ignored = new NetworkInterceptor(driver, myFilter);
        
        
        //https://www.elpais.com/
        //https://www.elmundo.es/
        //https://okdiario.com/
        //https://www.publico.es/
        //https://www.elcorteingles.es/
        //https://www.dia.es/

        String domain = "https://www.elmundo.es/";
        String domain_without_protocol = "www.elmundo.es/";
        String short_domain = "elmundo.es";
        driver.get(domain);

        
        try{
            wait.until(_d -> content.size() > 150);
        } catch (org.openqa.selenium.TimeoutException e){
            System.out.println("\n\n\n");
            System.out.println("Number of caught files: " + content.size());
            System.out.println("\n\n\n");
        }

        driver.quit();

        //////////////////////////////////////////////////////////////////////////////
        
        List<String> urls = new ArrayList<>();

        for (int i = 0; i < content.size(); i++) {
            //System.out.println(contentType.get(i));
            String result = new String(content.get(i).get().readAllBytes());
            //System.out.println(result+ "\n\n\n\n\n\n\n");

            // Regex to match https:// followed by any non-space characters
            String regex = "https://[^\\s]+";

            Pattern pattern = Pattern.compile(regex);
            Matcher matcher = pattern.matcher(result);

            while (matcher.find()) {
                urls.add(matcher.group());
            }
        }


        String urlsSepartedByCommas = "";
        // Print results
        for (String url : urls) {

            String[] cuttedUrl =  url.split("[\"'\\\\]");

            if((cuttedUrl[0].contains("privacidad") || cuttedUrl[0].contains("cookies")) && cuttedUrl[0].contains(short_domain)){
                urlsSepartedByCommas = urlsSepartedByCommas + cuttedUrl[0] + ", ";
            }
        }

        if(urlsSepartedByCommas.equals("")){
            System.out.println("No URL's found.");
            return;
        }

        urlsSepartedByCommas = urlsSepartedByCommas.substring(0, urlsSepartedByCommas.length() - 2);

        





        ////////////////////////////////////////////////////////////


        Client client = new Client();

        GenerateContentResponse responseCookie = client.models.generateContent(
            "gemini-2.5-flash",
            "From these URL's ("+urlsSepartedByCommas+"), found when parsing "+short_domain+" html and js files, which do you think is the cookie policy webpage. Just return one URL.",
            null);

        System.out.println();
        System.out.println("Gemini guess for Cookies information: "+responseCookie.text());

        GenerateContentResponse responsePrivacy = client.models.generateContent(
            "gemini-2.5-flash",
            "From these URL's ("+urlsSepartedByCommas+"), found when parsing "+short_domain+" html and js files, which do you think is the privacy policy webpage. Just return one URL.",
            null);

        System.out.println();
        System.out.println("Gemini guess for Privacy information: "+responsePrivacy.text());

        



        ////////////////////////////////////////////////////////////

        try{
            ProcessBuilder builder = new ProcessBuilder("bash", "-c", "wget -P ./cookies --no-check-certificate -p -k "+responseCookie.text());
            Process process = builder.start();
            int exitCode = process.waitFor();
            
            builder = new ProcessBuilder("bash", "-c", "wget -P ./privacidad --no-check-certificate -p -k "+responsePrivacy.text());
            process = builder.start();
            exitCode = process.waitFor();

        } catch (Exception e) {
            e.printStackTrace();
        }
























        String privacyHtml = "";
        String cookiesHtml = "";
        String privacyFilePath = "./privacidad/"+domain_without_protocol+"/privacidad/index.html";
        String cookiesFilePath = "./cookies/"+domain_without_protocol+"/cookies.html";
        
        try {
            privacyHtml = Files.readString(Path.of(privacyFilePath),StandardCharsets.ISO_8859_1);
            cookiesHtml = Files.readString(Path.of(cookiesFilePath),StandardCharsets.ISO_8859_1);
            
        } catch (IOException e) {
            // Handle exceptions like File Not Found or I/O errors
            System.err.println("Error reading file: " + e.getMessage());
            e.printStackTrace();
        }


        String promptArray[] = new String[3];
        
        promptArray[0] = """

        Role: Act as a Senior GDPR and ePrivacy Compliance Auditor.

        Task: You will analyze the content of two provided legal documents in HTML format (Privacy Policy and Cookie Policy) against a specific compliance checklist and output the results in a strict JSON format.

        Input Data:
        
        """;

        promptArray[1] = 
        "\nPrivacy Policy HTML file: [" + privacyHtml + "]" +
        "\nCookie Policy HTML file: [" + cookiesHtml + "]" +
        "\nCookies inventory: not provided";

        promptArray[2] = """

        Instructions:

        Read and analyze the content of the documents provided above.

        Evaluate the \"Audit Checklist\" questions below.

        CRITICAL: For every answer, determine the \"Verdict\" (Yes / No / Partial) and extract \"Evidence\" (direct quote).

        SCORING: Calculate the score internally:

        Yes = 2 points

        Partial = 1 point

        No/Not Found = 0 points

        Total possible: 34 points.

        Levels: 0-15 (Critical Risk), 16-24 (High Risk), 25-30 (Moderate Risk), 31-34 (Low Risk / Compliant).

        AUDIT CHECKLIST (To be analyzed):

        PART A: GENERAL GOVERNANCE & DATA SUBJECT RIGHTS

        Does the policy clearly state the full contact details of the Data Controller (company name, address) and the Data Protection Officer (DPO), if applicable?

        Does the policy specify the retention period (how long data is kept) for the main categories of personal data collected?

        Does the policy list the specific user rights (Access, Rectification, Erasure, Objection, Portability)?

        Is there an operational contact channel (specific email or form) and clear instructions on how to exercise these rights?

        Is the right to lodge a complaint with the relevant supervisory authority mentioned?

        If data leaves the EEA, does the policy identify the recipient country and the specific safeguards used (e.g., Standard Contractual Clauses/SCCs or Data Privacy Framework)?

        PART B: COOKIES & TRACKING TRANSPARENCY 7. Is there a specific and accessible Cookie Policy? (Is it separate or clearly integrated within the Privacy Policy?) 8. Does it explain in plain language what cookies are and why they are used on this website? 9. Are cookie categories clearly defined? (e.g., Technical, Analytical, Marketing, Preferences). 10. Are \"strictly necessary\" cookies explained, and is it justified why these do not require prior consent? 11. Does the policy contain a table or list detailing every cookie, including: Name, Provider, Purpose, and Duration? 12. Are there links to the privacy policies of external providers (third parties like Google, Facebook)? 13. Does it explicitly state that non-essential cookies (analytics/marketing) are only installed after consent? 14. Is the legal basis identified for each cookie type? (e.g., \"Legitimate Interest/Necessity\" for essential ones; \"Consent\" for the rest). 15. Does the text explain how the user can withdraw or modify their consent at any time? (Must mention a settings panel, footer link, or similar). 16. Does it clarify that withdrawing consent is as easy as giving it (e.g., \"you can change your mind at any time\")? 17. Does it mention if cookies are used for user profiling or tracking?

        OUTPUT FORMAT (STRICT JSON)
        Provide the response ONLY as a valid JSON object. Do not include introductory text or markdown formatting (like ```json). Use exactly the following structure:

        JSON

        {
          \"audit_meta\": {
            \"auditor_role\": \"Senior GDPR & ePrivacy Compliance Auditor\",
            \"target_entity\": \"European Parliament\",
            \"documents_reviewed\": [
              \"Privacy Policy\",
              \"Cookie Policy\",
              \"Cookies Inventory\"
            ],
            \"audit_date\": \"YYYY-MM-DD\"
          },
          \"audit_checklist\": [
            {
              \"id\": 1,
              \"category\": \"PART A: GENERAL GOVERNANCE\",
              \"question\": \"Insert the FULL question text here\",
              \"verdict\": \"Yes / No / Partial\",
              \"evidence\": \"Insert direct quote here\",
              \"notes\": \"Insert your auditor analysis here\"
            },
            {
              \"id\": 2,
              \"...\" : \"...\"
            }
            // Continue for all 17 questions
          ],
          \"scorecard\": {
            \"total_score\": 0, // Sum of points
            \"max_score\": 34,
            \"compliance_level\": \"INSERT LEVEL NAME\",
            \"risk_icon\": \"🔴 / 🟠 / 🟡 / 🟢\",
            \"priority_actions\": [
              \"Action 1 based on negative results\",
              \"Action 2 based on negative results\",
              \"Action 3 based on negative results\"
            ]
          }
        }

        """;

        GenerateContentResponse responseGDPR = client.models.generateContent(
            "gemini-2.5-flash",
            promptArray[0]+promptArray[1]+promptArray[2],
            null);

        System.out.println();
        System.out.println("Gemini GDPR response: "+responseGDPR.text());

        Runtime.getRuntime().exec("rm -rf privacidad");
        Runtime.getRuntime().exec("rm -rf cookies");


    }
}
